In [22]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,3,0])
print('A+B = ',np.add(A,B))
print('A-B = ',np.subtract(A,B))

A+B =  [5 5 3]
A-B =  [-3 -1  3]


In [27]:
C = np.array([[1,2,3],[1,1,1]])
D = np.array([[4,3,9,9],
            [1,1,2,2],
            [4,2,1,1]])
print('C@D = ',np.matmul(C,D))
print('C@D = ',C@D)
print('np.multiply(D,D)= ',np.multiply(D,D))
print('D*D = ',D*D)

C@D =  [[18 11 16 16]
 [ 9  6 12 12]]
C@D =  [[18 11 16 16]
 [ 9  6 12 12]]
np.multiply(D,D)=  [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]
D*D =  [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]


In [1]:
import tensorflow as tf